### ISSUE TITLE
list *background same as sidebar background

### ISSUE THREAD

**Issue by t7yang** [mikeybell/supernova-color-theme#1]
for example `list.activeSelectionBackground` should not same color with `sideBar.background`, cause you can't tell which file currently active:
![explorer-highlight](https://user-images.githubusercontent.com/4502661/53461507-b8f58f80-3a7b-11e9-80c6-4100c5695068.jpg)

**Comment by mikeybell** [comment]
Thanks for the hot tip. I will adjust that

**Comment by mikeybell** [comment]
Hey just checked this out and these two colors are actually different. `
list.activeSelectionBackground` should be a darker shade than the `
sideBar.background`. Is that not what you are seeing?

```
"sideBar.background": "#1C222D"
"list.activeSelectionBackground": "#141820"
```

**Comment by t7yang** [comment]
Yes, Microsoft naming is quite "interesting", directive that actually affect for currently selected tab is `list.inactiveSelectionBackground`:
![2c719135-88e9-45f0-8ba3-baa025fb7de4 png](https://user-images.githubusercontent.com/4502661/53659496-ad31e500-3c96-11e9-8f37-a3bef51b9f0d.jpg)

**Comment by mikeybell** [comment]
Just published a new version :) Honestly, I don't see a difference, so let me know if this helps you out.

**Comment by t7yang** [comment]
Maybe the difference between mac and windows, I not sure too, but the screen capture show you what actually the difference, it is no way to distinguish if inactive selection background color same as sidebar background color.

**Comment by mikeybell** [comment]
Yeah this is great feedback, so thank you. Let me know if this fixes the issue for you.

**Comment by t7yang** [comment]
Yes, problem solved.
