### ISSUE TITLE
font

### ISSUE THREAD

**Issue by Goatmaster** [mikeybell/supernova-color-theme#2]
Hey, 

what font are you using in your sreenshots?

Thanks

**Comment by mikeybell** [comment]
The font is called Menlo. Here is the font stack I go with: `Menlo, Monaco, 'Courier New', monospace`

**Comment by mikeybell** [comment]
You can edit this in preferences > settings > Editor: Font Family

**Comment by Goatmaster** [comment]
Thank you.
